import { useContext, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { listContext } from "./context";
import Modal from "../component/Modal";

const Home: NextPage = () => {
  const [modal, setModal] = useState(false);
  const names = useContext(listContext);
  const modalToggle = () => {
    setModal(!modal);
  };
  return (
    <div>
      <Head>
        <title>next modal tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center p-2">
        <button
          onClick={modalToggle}
          className="mt-2 border px-5 py-1.5 bg-blue-400 rounded-lg font-semibold text-white hover:bg-blue-700"
        >
          Add List
        </button>
      </div>
      {modal ? <Modal toggle={modalToggle}/> : null}
      <ul>
        {names.map((n, i) => (
          <li key={i}>{n}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
